/*
 * CalculatorServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package org.example.models;

import java.util.*;

public class AddBuilder {
    //the instance to build
    private Add add;

    /**
     * Default constructor to initialize the instance
     */
    public AddBuilder() {
        add = new Add();
    }

    public AddBuilder a(Integer a) {
        add.setA(a);
        return this;
    }

    public AddBuilder b(Integer b) {
        add.setB(b);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Add build() {
        return add;
    }
}