/*
 * CalculatorServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package org.example.models;

import java.util.*;

public class AddResponseBuilder {
    //the instance to build
    private AddResponse addResponse;

    /**
     * Default constructor to initialize the instance
     */
    public AddResponseBuilder() {
        addResponse = new AddResponse();
    }

    public AddResponseBuilder result(Integer result) {
        addResponse.setResult(result);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public AddResponse build() {
        return addResponse;
    }
}