/*
 * CalculatorServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package org.example.models;

import java.util.*;

public class ICalculatorAddOutputMessageBuilder {
    //the instance to build
    private ICalculatorAddOutputMessage iCalculatorAddOutputMessage;

    /**
     * Default constructor to initialize the instance
     */
    public ICalculatorAddOutputMessageBuilder() {
        iCalculatorAddOutputMessage = new ICalculatorAddOutputMessage();
    }

    public ICalculatorAddOutputMessageBuilder parameters(AddResponse parameters) {
        iCalculatorAddOutputMessage.setParameters(parameters);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ICalculatorAddOutputMessage build() {
        return iCalculatorAddOutputMessage;
    }
}