/*
 * CalculatorServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package org.example.models;

import java.util.*;

public class ICalculatorSubtractOutputMessageBuilder {
    //the instance to build
    private ICalculatorSubtractOutputMessage iCalculatorSubtractOutputMessage;

    /**
     * Default constructor to initialize the instance
     */
    public ICalculatorSubtractOutputMessageBuilder() {
        iCalculatorSubtractOutputMessage = new ICalculatorSubtractOutputMessage();
    }

    public ICalculatorSubtractOutputMessageBuilder parameters(SubtractResponse parameters) {
        iCalculatorSubtractOutputMessage.setParameters(parameters);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ICalculatorSubtractOutputMessage build() {
        return iCalculatorSubtractOutputMessage;
    }
}