/*
 * CalculatorServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package org.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ICalculatorAddOutputMessage 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4780179681923427510L;
    private AddResponse parameters;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("parameters")
    public AddResponse getParameters ( ) { 
        return this.parameters;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("parameters")
    public void setParameters (AddResponse value) { 
        this.parameters = value;
    }
 
}
 