/*
 * CalculatorServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package org.example.models;

import java.util.*;

public class ICalculatorAddInputMessageBuilder {
    //the instance to build
    private ICalculatorAddInputMessage iCalculatorAddInputMessage;

    /**
     * Default constructor to initialize the instance
     */
    public ICalculatorAddInputMessageBuilder() {
        iCalculatorAddInputMessage = new ICalculatorAddInputMessage();
    }

    public ICalculatorAddInputMessageBuilder parameters(Add parameters) {
        iCalculatorAddInputMessage.setParameters(parameters);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ICalculatorAddInputMessage build() {
        return iCalculatorAddInputMessage;
    }
}