/*
 * CalculatorServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package org.example.models;

import java.util.*;

public class SubtractResponseBuilder {
    //the instance to build
    private SubtractResponse subtractResponse;

    /**
     * Default constructor to initialize the instance
     */
    public SubtractResponseBuilder() {
        subtractResponse = new SubtractResponse();
    }

    public SubtractResponseBuilder result(Integer result) {
        subtractResponse.setResult(result);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SubtractResponse build() {
        return subtractResponse;
    }
}