/*
 * CalculatorServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package org.example.models;

import java.util.*;

public class SubtractBuilder {
    //the instance to build
    private Subtract subtract;

    /**
     * Default constructor to initialize the instance
     */
    public SubtractBuilder() {
        subtract = new Subtract();
    }

    public SubtractBuilder a(Integer a) {
        subtract.setA(a);
        return this;
    }

    public SubtractBuilder b(Integer b) {
        subtract.setB(b);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Subtract build() {
        return subtract;
    }
}